; platformio.ini — CoolCycle Firmware
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = custom_partitions.csv
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  paulstoffregen/OneWire
  milesburton/DallasTemperature
  adafruit/DHT sensor library
  adafruit/Adafruit INA219
  adafruit/RTClib
  adafruit/Adafruit BH1750
  mikalhart/TinyGPSPlus
  me-no-dev/ESPAsyncWebServer
  me-no-dev/AsyncTCP
  bblanchon/ArduinoJson
  knolleary/PubSubClient
  vshymanskyy/TinyGSM

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -DBOARD_HAS_PSRAM=0
  -DTINY_GSM_MODEM_SIM800
